# Generated by Django 2.0.6 on 2018-07-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Biswanath',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
