# Generated by Django 2.0.5 on 2018-07-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20180724_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post_like',
        ),
        migrations.RemoveField(
            model_name='like',
            name='userprofile',
        ),
        migrations.AddField(
            model_name='like',
            name='nothing',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
