# Generated by Django 2.0.5 on 2018-07-25 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('post', '0006_auto_20180725_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='nothing',
        ),
        migrations.AddField(
            model_name='like',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AddField(
            model_name='like',
            name='post_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='like',
            name='userprofile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='core.UserProfile'),
        ),
    ]
