# Generated by Django 2.0.6 on 2018-07-25 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20180725_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='userprofile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='post_userprofile', to='core.UserProfile'),
        ),
    ]
