# Generated by Django 2.1 on 2018-08-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('post', '0009_auto_20180806_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='userprofile',
        ),
        migrations.AddField(
            model_name='like',
            name='userprofile',
            field=models.ManyToManyField(default=0, related_name='post_userprofile', to='core.UserProfile'),
        ),
    ]
