# Generated by Django 2.1 on 2018-08-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20180806_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post_like',
        ),
    ]
