# Generated by Django 2.0.5 on 2018-07-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=250)),
                ('test_about', models.CharField(max_length=1000)),
                ('test_id', models.IntegerField()),
            ],
        ),
    ]
